image:
- Visual Studio 2017
- Ubuntu
build_script:
- pwsh: |
    git submodule update --init --recursive
    dotnet build --configuration Debug    
    dotnet build --configuration Release    
    dotnet test
    
