language: csharp
mono: none
solution: Heroes.Models.sln
dotnet: 2.1.300
os:
  - linux
  - osx
script:
  - dotnet build --configuration Debug
  - dotnet build --configuration Release
  - dotnet test -c Release --no-build
