parameters:
  name: ''
  pool: ''

jobs:
  - job: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    variables:
      config_debug: debug
      config_release: release
    strategy:
      matrix:
        DEBUG:
          configuration: $(config_debug)
          CONFIG: $(config_debug)
        RELEASE:
          configuration: $(config_release)   
          CONFIG: $(config_release)
    steps:
    - script: dotnet build -c $(configuration)
      displayName: Build $(CONFIG)
 
    - script: dotnet test -c $(configuration) --no-build
      displayName: Test $(CONFIG)
