parameters:
  name: ''
  pool: ''

jobs:
  - job: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    variables:
      config_debug: debug
      config_release: release
    strategy:
      matrix:
        Build_Debug:
          configuration: $(config_debug)
        Build_Release:
          configuration: $(config_release)
    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: '2.2.100'
        
    - script: dotnet build -c $(configuration)
      displayName: Build
 
##    - script: dotnet test -c $(configuration) --no-build
##      displayName: Run tests
      
    - task: DotNetCoreCLI@2
      displayName: Run tests
      inputs:
        command: test
        configuration: $(configuration)
        nobuild: true
        publishTestResults: true
      
#    - task: PublishTestResults@2
#      inputs:
#        testResultsFormat: 'VSTtest'
#        testResultsFiles: '**/TEST-*.trx'
 #       

        
