variables:
  config_debug: debug
  config_release: release

- job: Linux
  strategy:
    matrix:
      _DEBUG:
        configuration: $(config_debug)
      _RELEASE:
        configuration: $(config_release)    
steps:
- script: dotnet build -c $(configuration)
  displayName: Build $(configuration)
  
#- job: Windows
#  pool:
#    vmImage: 'vs2017-win2016'
#  steps:
#  - script: echo hello from Windows
#  
#- job: macOS
#  pool:
#    vmImage: 'macOS-10.13'
#  steps:
#  - script: echo hello from macOS
#  
#- job: Linux
#  pool:
#    vmImage: 'ubuntu-16.04'
#  steps:
#  - script: echo hello from Linux
